### ISSUE TITLE
ZMQError: Socket operation on non-socket with example udpping3.py

### ISSUE THREAD

**Issue by scrool** [booksbyus/zguide#715]
When I try `udpping3.py` and hit Ctrl+C to interrupt the program I get a traceback with error `ZMQError: Socket operation on non-socket`:
```
$ python udpping3.py 
Found peer 192.168.1.137:9999
['JOINED', '01f1b59231764528a9b1725b04ae9229']
interrupted
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/scrool/workspace/zguide/examples/Python/interface.py", line 119, in start
    loop.start()
  File "/home/scrool/.virtualenvs/zguide/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/scrool/.virtualenvs/zguide/lib/python2.7/site-packages/zmq/eventloop/minitornado/ioloop.py", line 861, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/home/scrool/.virtualenvs/zguide/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 122, in poll
    z_events = self._poller.poll(1000*timeout)
  File "/home/scrool/.virtualenvs/zguide/lib/python2.7/site-packages/zmq/sugar/poll.py", line 99, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll
  File "zmq/backend/cython/_poll.pyx", line 116, in zmq.backend.cython._poll.zmq_poll
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
    raise ZMQError(errno)
ZMQError: Socket operation on non-socket
```

I *guess* class `InterfaceAgent` shouldn't close pipe in its `stop()` method - it is closed in class `Interface` just before this agent stop method is called. This fixes the traceback:
```
diff --git a/examples/Python/interface.py b/examples/Python/interface.py
index 6b2a1b81..cc94fd4b 100644
--- a/examples/Python/interface.py
+++ b/examples/Python/interface.py
@@ -98,7 +98,6 @@ class InterfaceAgent(object):
         self.peers = {}
 
     def stop(self):
-        self.pipe.close()
         self.loop.stop()
 
     def __del__(self):
```

But I guess there is something else missing because now `stop()` method of class `Interface` gets stuck on context termination. I have to hit one more Ctrl+C to interrupt the program and I end up with different traceback:
```
$ python udpping3.py 
Found peer 192.168.1.137:9999
['JOINED', 'f6e9be6834af4ce583f940f128db3a3f']
Found peer 192.168.1.137:9999
Found peer 192.168.1.137:9999
interrupted
Traceback (most recent call last):
  File "udpping3.py", line 18, in <module>
    main()
  File "udpping3.py", line 15, in main
    interface.stop()
  File "/home/scrool/workspace/zguide/examples/Python/interface.py", line 46, in stop
    self.ctx.term()
  File "zmq/backend/cython/context.pyx", line 136, in zmq.backend.cython.context.Context.term
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt
```

I'm run this on Fedora 26 in virtualenv:
Current libzmq version is 4.1.6
Current  pyzmq version is 16.0.3
```
$ python version.py 
Current libzmq version is 4.1.6
Current  pyzmq version is 16.0.3
$ pip freeze
pyzmq==16.0.3
$ python --version
Python 2.7.14
```

**Comment by sappo** [comment]
@scrool thanks for your error report. This issue tracker is rather low latency and sadly I'm not a python guy. Thus I recommend you write to the zeromq mailing list :)

**Comment by scrool** [comment]
Thanks @sappo. Just for a reference I sent e-mail to mailing list: https://lists.zeromq.org/pipermail/zeromq-dev/2017-December/032157.html

And in the end I guess I have a patch (see my later response there). Soon I'll open a PR.
